DROP TABLE users CASCADE;
DROP TABLE guides CASCADE;
DROP TABLE comments CASCADE;
DROP TABLE contributions CASCADE;
DROP TABLE steps CASCADE;
DROP TABLE step_contributions CASCADE;
DROP TABLE tips CASCADE;
DROP TABLE source_citations CASCADE;
